id: P004562
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG18535
  title: ཤ་ཡི་ཉེས་དམིགས།
  author: ''
  volumes:
    a14b0103ad78447fbb9730789702749b:
      image_group_id: I1KG18555
      title: ''
      volume_number: 1
      total_pages: 72
      base_file: v001.txt
